#!/usr/bin/env bash
#
# Package the Autobom SketchUp extension into autobom_skp.rbz at repo root.
#
# HtmlDialog loads a remote URL only (no bundled UI). Requires AUTOBOM_HTML_DIALOG_URL
# in repo-root .env (next to package.json).
#
# Usage:
#   ./package-extensions.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

to_win_path() {
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -w "$1"
  elif [[ "$1" =~ ^/[a-zA-Z]/(.*)$ ]]; then
    local drive
    drive="$(echo "${BASH_REMATCH[0]:1:1}" | tr '[:lower:]' '[:upper:]')"
    echo "${drive}:\\${BASH_REMATCH[1]//\//\\}"
  else
    echo "$1"
  fi
}

EXT_NAME="autobom_skp"
SRC="${SCRIPT_DIR}/${EXT_NAME}"

if [[ ! -d "${SRC}" ]]; then
  echo "❌ Missing extension source: ${SRC}"
  exit 1
fi

ROOT_ENV="${SCRIPT_DIR}/.env"
if [[ ! -f "${ROOT_ENV}" ]]; then
  echo "❌ Missing ${ROOT_ENV}"
  echo "   Copy .env.example to .env and set AUTOBOM_HTML_DIALOG_URL to your hosted autobom_ui index URL, then retry."
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "${ROOT_ENV}"
set +a

if [[ -z "${AUTOBOM_HTML_DIALOG_URL:-}" ]]; then
  echo "❌ AUTOBOM_HTML_DIALOG_URL must be set in ${ROOT_ENV}"
  exit 1
fi
if [[ ! "${AUTOBOM_HTML_DIALOG_URL}" =~ ^https?:// ]]; then
  echo "❌ AUTOBOM_HTML_DIALOG_URL must start with http:// or https://"
  exit 1
fi

rm -f "${SCRIPT_DIR}/${EXT_NAME}.rbz"

BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "${BUILD_DIR}"' EXIT

echo "📦 Packaging ${EXT_NAME}..."

cat > "${BUILD_DIR}/${EXT_NAME}.rb" << 'LOADER_EOF'
# frozen_string_literal: true

require "sketchup.rb"

require File.join(__dir__, "autobom_skp", "browser_dialog")

module AutobomModelBrowser
  PLUGIN_NAME = "Autobom"
  DEFAULT_API_BASE = "http://127.0.0.1:3847"

  unless file_loaded?(__FILE__)
    menu = UI.menu("Plugins")
    menu.add_item(PLUGIN_NAME) { BrowserDialog.show }

    toolbar = UI::Toolbar.new(PLUGIN_NAME)

    cmd = UI::Command.new(PLUGIN_NAME) { BrowserDialog.show }
    cmd.tooltip = PLUGIN_NAME
    cmd.status_bar_text = "Browse Autobom — import catalog GLB or SKP models"

    icons_dir = File.join(__dir__, "autobom_skp", "icons")
    small_icon = File.join(icons_dir, "browser_small.png")
    large_icon = File.join(icons_dir, "browser_large.png")

    cmd.small_icon = small_icon
    cmd.large_icon = large_icon

    toolbar.add_item(cmd)

    tb_visible = defined?(UI::Toolbar::TB_VISIBLE) ? UI::Toolbar::TB_VISIBLE : 1
    if toolbar.get_last_state == tb_visible
      toolbar.restore
    else
      toolbar.hide
    end

    file_loaded(__FILE__)
  end
end
LOADER_EOF

mkdir -p "${BUILD_DIR}/${EXT_NAME}"
cp "${SRC}/browser_dialog.rb" "${BUILD_DIR}/${EXT_NAME}/"
cp "${SRC}/http_client.rb" "${BUILD_DIR}/${EXT_NAME}/"
cp "${SRC}/zip_extract.rb" "${BUILD_DIR}/${EXT_NAME}/"
cp -r "${SRC}/icons" "${BUILD_DIR}/${EXT_NAME}/"
URL_FOR_RUBY="$(node -e 'console.log(JSON.stringify(process.argv[1]))' -- "${AUTOBOM_HTML_DIALOG_URL}")"
cat > "${BUILD_DIR}/${EXT_NAME}/ui_config.rb" <<EOF
# frozen_string_literal: true
# Generated by package-extensions.sh — rebuild the .rbz to change this URL.

module AutobomModelBrowser
  PACKAGED_HTML_DIALOG_URL = ${URL_FOR_RUBY}.freeze
end
EOF
echo "🌐 Packaging HtmlDialog URL: ${AUTOBOM_HTML_DIALOG_URL}"

echo "📦 Creating ${EXT_NAME}.rbz..."
cd "${BUILD_DIR}"
RBZ_PATH="${SCRIPT_DIR}/${EXT_NAME}.rbz"
if command -v zip >/dev/null 2>&1; then
  zip -r "${RBZ_PATH}" \
    "${EXT_NAME}.rb" \
    "${EXT_NAME}/" \
    -x "*.DS_Store" -x "*__MACOSX*"
else
  ZIP_PATH="${BUILD_DIR}/${EXT_NAME}.zip"
  ZIP_WIN="$(to_win_path "${ZIP_PATH}")"
  powershell.exe -NoProfile -Command \
    "Compress-Archive -Path '${EXT_NAME}.rb','${EXT_NAME}' -DestinationPath '${ZIP_WIN}' -Force"
  mv "${ZIP_PATH}" "${RBZ_PATH}"
fi

cd "${SCRIPT_DIR}"

echo ""
echo "✅ Packaged successfully: ${EXT_NAME}.rbz"
echo ""
if command -v ls >/dev/null 2>&1; then
  ls -lh "${EXT_NAME}.rbz"
else
  powershell.exe -NoProfile -Command "(Get-Item '${SCRIPT_DIR}/${EXT_NAME}.rbz').Length"
fi
echo ""
echo "📋 Contents:"
if command -v unzip >/dev/null 2>&1; then
  unzip -l "${EXT_NAME}.rbz"
else
  RBZ_WIN="$(to_win_path "${SCRIPT_DIR}/${EXT_NAME}.rbz")"
  powershell.exe -NoProfile -Command \
    "Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::OpenRead('${RBZ_WIN}').Entries | ForEach-Object { \$_.FullName }"
fi
echo ""
echo "📋 Install in SketchUp: Extension Manager → Install Extension → ${EXT_NAME}.rbz"
